

	
matrix.o: matrix.cpp matrix.h
	$(CXX) $(CXXFLAGS) -c matrix.o matrix.cpp



sfuns.o : sfuns.cpp sfuns.h
	$(CXX) $(CXXFLAGS) -c sfuns.o sfuns.cpp #-c stands for compile only




clean:
	$(RM)  *.o 
