vec.o: vec.cpp vec.h sfuns.h
	$(CXX) $(CXXFLAGS) -c vec.o vec.cpp

matrix.o: matrix.cpp matrix.h
	$(CXX) $(CXXFLAGS) -c matrix.o matrix.cpp



sfuns.o : sfuns.cpp sfuns.h
	$(CXX) $(CXXFLAGS) -c sfuns.o sfuns.cpp #-c stands for compile only




clean:
	$(RM)  *.o 
